{
 "title": "Similarity API",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "AVG Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"similarity-api\"}[5m]) / rate(http_request_duration_seconds_count{job=\"similarity-api\"}[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"similarity-api\"}[$__rate_interval])",
     "legendFormat": "CPU Seconds"
    }
   ]
  },
  {
   "title": "RPM HTTP Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler!=\"/metrics\"}[1m])",
     "legendFormat": "{{status}}-{{job}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"similarity-api\"}",
     "legendFormat": "Memory Bytes"
    }
   ]
  },
  {
   "title": "NDCG (Atual)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "select\r\n  created_at,\r\n  score\r\nfrom\r\n  ndcg_results\r\nwhere\r\n  created_at >= DATE_ADD(CURRENT_DATE, interval -5 day)\r\norder by created_at desc\r\nlimit 1"
    }
   ]
  },
  {
   "title": "NDCG (Histórico)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "select\r\n  created_at,\r\n  score\r\nfrom\r\n  ndcg_results\r\nwhere\r\n  created_at >= DATE_ADD(CURRENT_DATE, interval -5 day)\r\norder by created_at desc"
    }
   ]
  }
 ]
}